// <auto-generated />
namespace GoodSamaritan.Migrations.ClientMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SmartValidateLookup2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SmartValidateLookup2));
        
        string IMigrationMetadata.Id
        {
            get { return "201503060509550_SmartValidateLookup2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
