// <auto-generated />
namespace GoodSamaritan.Migrations.ClientMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class allowNullableDatesInClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allowNullableDatesInClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201504080529382_allowNullableDatesInClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
