// <auto-generated />
namespace goodSamaritan.Migrations.ClientMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addedto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedto));
        
        string IMigrationMetadata.Id
        {
            get { return "201503010402021_added to"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
